# Generated by Django 2.2.16 on 2020-10-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tejido', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('localizacion', models.CharField(max_length=200)),
            ],
        ),
    ]
