# Generated by Django 2.2.16 on 2020-10-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioTelas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela',
            name='foto',
            field=models.ImageField(default='FotoTela', upload_to='telas'),
        ),
    ]
